name: bio_clinical_mbert
channels:
  - pytorch
  - huggingface
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - transformers
  - pip:
    - torch
    - scikit-learn
    - seqeval
    - tensorboard
    - nvitop
    - jupyter 
    - notebook
    - ipykernel